# Generated by Django 3.2.20 on 2023-09-05 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloud_photo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ('-created_time',), 'verbose_name': '照片模型'},
        ),
    ]
